export const budgetsText = {
  title: 'Anggaran',
  addLabel: 'Tambah anggaran',
  previousMonth: 'Bulan sebelumnya',
  nextMonth: 'Bulan berikutnya',
  currentMonth: 'Bulan ini',
  loadError: 'Anggaran gagal dimuat.',
  retry: 'Coba lagi',
  empty: {
    title: 'Belum ada anggaran',
    description: 'Tetapkan batas pengeluaran per kategori agar arus kas tetap terjaga.',
    cta: 'Buat anggaran',
  },
  summary: {
    allocated: 'Total anggaran',
    spent: 'Terpakai',
    remaining: 'Sisa',
    over: 'Melebihi',
  },
  progress: {
    used: 'terpakai',
    remaining: 'Sisa',
    over: 'Lebih',
  },
  form: {
    createTitle: 'Buat anggaran',
    editTitle: 'Ubah anggaran',
    monthLabel: 'Bulan',
    monthPlaceholder: 'YYYY-MM',
    monthHint: 'Format tahun-bulan, contoh 2026-07.',
    categoryLabel: 'Kategori pengeluaran',
    categoryPlaceholder: 'Pilih kategori',
    categoryPickerTitle: 'Pilih kategori pengeluaran',
    amountLabel: 'Batas anggaran',
    amountPlaceholder: '0',
    immutableHint: 'Bulan dan kategori tidak dapat diubah. Hapus lalu buat baru jika keliru.',
    save: 'Simpan',
    pending: 'Memproses…',
    delete: 'Hapus',
  },
  validation: {
    monthRequired: 'Bulan wajib diisi.',
    monthInvalid: 'Bulan harus memakai format YYYY-MM yang valid.',
    categoryRequired: 'Kategori pengeluaran wajib dipilih.',
    categoryInvalid: 'Kategori yang dipilih harus bertipe pengeluaran.',
    amountRequired: 'Batas anggaran wajib diisi.',
    amountInvalid: 'Batas anggaran harus bilangan bulat lebih dari nol.',
  },
  noExpenseCategories: 'Belum ada kategori pengeluaran. Buat kategori terlebih dahulu.',
  confirmDelete: {
    title: 'Hapus anggaran?',
    description: (category: string, month: string) =>
      `Anggaran ${category} untuk ${month} akan dihapus.`,
    confirm: 'Hapus',
  },
  toasts: {
    created: 'Anggaran dibuat.',
    updated: 'Anggaran diperbarui.',
    deleted: 'Anggaran dihapus.',
  },
} as const
