// All copy for the product catalogue. Stock and cost are displayed here, but
// are changed only by the transaction/domain workflow.
export const productsText = {
  title: 'Produk',
  backLabel: 'Kembali',
  addLabel: 'Tambah produk',
  archivedSection: 'Diarsipkan',
  loadError: 'Daftar produk gagal dimuat.',
  retry: 'Coba lagi',
  empty: {
    title: 'Belum ada produk',
    description: 'Tambahkan produk untuk mencatat stok dan laba penjualan.',
    cta: 'Tambah produk',
  },
  labels: {
    stock: 'Stok',
    skuMissing: 'SKU belum diatur',
    cost: 'Modal rata-rata',
    salePrice: 'Harga jual',
    movement: 'Mutasi',
    profit: 'Laba',
  },
  detail: {
    title: 'Detail produk',
    history: 'Riwayat stok & laba',
    noHistory: 'Belum ada transaksi produk.',
    loadError: 'Riwayat produk gagal dimuat.',
    retry: 'Coba lagi',
    purchase: 'Pembelian',
    sale: 'Penjualan',
    edit: 'Edit produk',
  },
  form: {
    createTitle: 'Tambah produk',
    editTitle: 'Edit produk',
    nameLabel: 'Nama produk',
    namePlaceholder: 'Contoh: Kopi susu 250 ml',
    skuLabel: 'SKU',
    skuPlaceholder: 'Opsional',
    unitLabel: 'Satuan',
    unitPlaceholder: 'Contoh: pcs',
    salePriceLabel: 'Harga jual',
    salePricePlaceholder: '0',
    save: 'Simpan',
    pending: 'Memproses…',
    archive: 'Arsipkan',
    unarchive: 'Aktifkan lagi',
    delete: 'Hapus',
  },
  validation: {
    nameRequired: 'Nama produk wajib diisi.',
    nameTooLong: 'Nama produk maksimal 80 karakter.',
    skuTooLong: 'SKU maksimal 60 karakter.',
    unitRequired: 'Satuan wajib diisi.',
    unitTooLong: 'Satuan maksimal 20 karakter.',
    salePriceRequired: 'Harga jual wajib diisi.',
    salePriceInvalid: 'Harga jual harus bilangan bulat nol atau lebih.',
  },
  confirmDelete: {
    title: 'Hapus produk?',
    description: (name: string) =>
      `Produk "${name}" akan dihapus dan tidak muncul lagi di katalog.`,
    confirm: 'Hapus',
  },
  toasts: {
    created: 'Produk ditambahkan.',
    updated: 'Produk diperbarui.',
    archived: 'Produk diarsipkan.',
    unarchived: 'Produk diaktifkan lagi.',
    deleted: 'Produk dihapus.',
  },
} as const
