export const recurringText = {
  title: 'Transaksi berulang',
  addLabel: 'Tambah aturan berulang',
  active: 'Aktif',
  inactive: 'Nonaktif',
  loadError: 'Aturan transaksi berulang gagal dimuat.',
  retry: 'Coba lagi',
  empty: {
    title: 'Belum ada aturan berulang',
    description: 'Buat aturan untuk transaksi rutin agar pencatatan lebih konsisten.',
    action: 'Buat aturan',
  },
  form: {
    createTitle: 'Buat aturan berulang',
    editTitle: 'Ubah aturan berulang',
    nameLabel: 'Nama aturan',
    namePlaceholder: 'Contoh: Tagihan internet',
    frequencyLabel: 'Frekuensi',
    monthly: 'Bulanan',
    weekly: 'Mingguan',
    dayLabel: 'Hari',
    monthlyDayHint: 'Isi tanggal 1 sampai 28 setiap bulan.',
    weeklyDayHint: 'Isi 1 (Senin) sampai 7 (Minggu).',
    nextRunAtLabel: 'Jalankan berikutnya',
    nextRunAtPlaceholder: 'YYYY-MM-DD',
    nextRunAtHint: 'Format tanggal contoh: 2026-08-01.',
    typeLabel: 'Jenis transaksi',
    income: 'Pemasukan',
    expense: 'Pengeluaran',
    amountLabel: 'Nominal',
    walletLabel: 'Dompet',
    walletPlaceholder: 'Pilih dompet',
    walletPickerTitle: 'Pilih dompet',
    categoryLabel: 'Kategori',
    categoryPlaceholder: 'Pilih kategori',
    categoryPickerTitle: 'Pilih kategori',
    channelLabel: 'Channel',
    channelPlaceholder: 'Pilih channel',
    channelPickerTitle: 'Pilih channel',
    optionalNone: 'Tidak ada',
    noteLabel: 'Catatan',
    notePlaceholder: 'Opsional',
    save: 'Simpan aturan',
    pending: 'Memproses…',
    delete: 'Hapus aturan',
  },
  validation: {
    nameRequired: 'Nama aturan wajib diisi.',
    nameTooLong: 'Nama aturan maksimal 80 karakter.',
    dayRequired: 'Hari wajib diisi.',
    dayMonthly: 'Untuk bulanan, isi tanggal 1 sampai 28.',
    dayWeekly: 'Untuk mingguan, isi hari 1 sampai 7.',
    nextRunAtRequired: 'Tanggal berikutnya wajib diisi.',
    nextRunAtInvalid: 'Tanggal berikutnya harus memakai format YYYY-MM-DD yang valid.',
    amountRequired: 'Nominal wajib diisi.',
    amountInvalid: 'Nominal harus bilangan bulat lebih dari nol.',
    walletRequired: 'Pilih dompet.',
    categoryRequired: 'Pilih kategori.',
    categoryInvalid: 'Kategori harus sesuai dengan jenis transaksi.',
    noteTooLong: 'Catatan maksimal 200 karakter.',
  },
  noWallets: 'Belum ada dompet aktif. Buat dompet terlebih dahulu.',
  noCategories: 'Belum ada kategori yang sesuai. Buat kategori terlebih dahulu.',
  confirmDelete: {
    title: 'Hapus aturan?',
    description: (name: string) => `Aturan ${name} akan dihapus permanen dari daftar.`,
    confirm: 'Hapus',
  },
  toasts: {
    created: 'Aturan berulang dibuat.',
    updated: 'Aturan berulang diperbarui.',
    deleted: 'Aturan berulang dihapus.',
    activated: 'Aturan berulang diaktifkan.',
    archived: 'Aturan berulang dinonaktifkan.',
  },
} as const
