// Transactions feature copy. Keep all user-facing Bahasa Indonesia text here.
export const transactionsText = {
  title: 'Transaksi',
  addLabel: 'Tambah transaksi',
  loadError: 'Daftar transaksi gagal dimuat.',
  retry: 'Coba lagi',
  filters: {
    all: 'Semua',
    allType: 'Semua jenis',
    allWallets: 'Semua dompet',
    allCategories: 'Semua kategori',
    allChannels: 'Semua channel',
    type: 'Jenis transaksi',
    allTime: 'Semua waktu',
    thisMonth: 'Bulan ini',
    period: 'Periode',
    income: 'Pemasukan',
    expense: 'Pengeluaran',
    transfer: 'Transfer',
    wallet: 'Dompet',
    category: 'Kategori',
    channel: 'Channel',
    clear: 'Reset filter',
  },
  empty: {
    title: 'Belum ada transaksi',
    description: 'Catat pemasukan, pengeluaran, atau transfer pertama Anda.',
    action: 'Tambah transaksi',
  },
  form: {
    createTitle: 'Tambah transaksi',
    editTitle: 'Edit transaksi',
    typeLabel: 'Jenis transaksi',
    amountLabel: 'Nominal',
    walletLabel: 'Dompet',
    walletPlaceholder: 'Pilih dompet',
    walletSheetTitle: 'Pilih dompet',
    counterWalletLabel: 'Dompet tujuan',
    counterWalletPlaceholder: 'Pilih dompet tujuan',
    counterWalletSheetTitle: 'Pilih dompet tujuan',
    categoryLabel: 'Kategori',
    categoryPlaceholder: 'Pilih kategori',
    categorySheetTitle: 'Pilih kategori',
    channelLabel: 'Channel',
    channelPlaceholder: 'Pilih channel',
    channelSheetTitle: 'Pilih channel',
    optionalNone: 'Tidak ada',
    dateLabel: 'Tanggal',
    noteLabel: 'Catatan',
    notePlaceholder: 'Opsional',
    itemsLabel: 'Detail produk',
    productLabel: 'Produk',
    productPlaceholder: 'Pilih produk',
    productSheetTitle: 'Pilih produk',
    quantityLabel: 'Jumlah',
    quantityPlaceholder: 'Contoh: 1',
    unitPriceLabel: 'Harga satuan',
    addItem: 'Tambah produk',
    itemTotal: 'Total item',
    itemsTotal: 'Total detail produk',
    removeItem: 'Hapus produk',
    noItems: 'Tambahkan produk bila transaksi ini memengaruhi stok.',
    save: 'Simpan transaksi',
    update: 'Simpan perubahan',
    cancel: 'Batal',
    delete: 'Hapus transaksi',
  },
  validation: {
    amountRequired: 'Nominal wajib diisi.',
    amountPositive: 'Nominal harus bilangan bulat lebih dari nol.',
    walletRequired: 'Pilih dompet.',
    counterWalletRequired: 'Pilih dompet tujuan.',
    sameWallet: 'Dompet asal dan tujuan tidak boleh sama.',
    categoryRequired: 'Pilih kategori.',
    dateRequired: 'Tanggal wajib diisi.',
    dateInvalid: 'Masukkan tanggal kalender yang valid (YYYY-MM-DD).',
    noteTooLong: 'Catatan maksimal 200 karakter.',
    productRequired: 'Pilih produk.',
    itemQtyRequired: 'Jumlah produk wajib diisi.',
    itemQtyPositive: 'Jumlah produk harus bilangan bulat lebih dari nol.',
    itemPriceRequired: 'Harga satuan wajib diisi.',
    itemPricePositive: 'Harga satuan harus bilangan bulat lebih dari nol.',
    itemsTotalMismatch: 'Nominal harus sama dengan total detail produk.',
    transferItems: 'Transfer tidak dapat memiliki detail produk.',
    duplicateProduct: 'Produk yang sama sudah ditambahkan.',
  },
  confirmDelete: {
    title: 'Hapus transaksi?',
    description: 'Transaksi ini akan dihapus dari daftar dan saldo terkait akan dihitung ulang.',
    confirm: 'Hapus',
  },
  toasts: {
    created: 'Transaksi berhasil dicatat.',
    updated: 'Perubahan transaksi disimpan.',
    deleted: 'Transaksi dihapus.',
  },
} as const
